import type { editor } from "monaco-editor";

export const VESPER_THEME_NAME = "vesper";
export const VESPER_LIGHT_THEME_NAME = "vesper-light";

// Vesper theme for Monaco — bg #101010, mint strings, lavender functions
export const VESPER_THEME_DATA: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "e8e8e8", background: "101010" },
    { token: "comment", foreground: "585858", fontStyle: "italic" },
    { token: "comment.line", foreground: "585858", fontStyle: "italic" },
    { token: "comment.block", foreground: "585858", fontStyle: "italic" },
    { token: "string", foreground: "99FFE4" },
    { token: "string.escape", foreground: "99FFE4" },
    { token: "string.quoted", foreground: "99FFE4" },
    { token: "string.template", foreground: "99FFE4" },
    { token: "number", foreground: "dbb96e" },
    { token: "number.float", foreground: "dbb96e" },
    { token: "number.hex", foreground: "dbb96e" },
    { token: "constant.numeric", foreground: "dbb96e" },
    { token: "keyword", foreground: "999999" },
    { token: "keyword.control", foreground: "999999" },
    { token: "keyword.operator", foreground: "999999" },
    { token: "storage", foreground: "999999" },
    { token: "storage.type", foreground: "999999" },
    { token: "entity.name.function", foreground: "B3A4F9" },
    { token: "entity.name.type", foreground: "B3A4F9" },
    { token: "entity.name.class", foreground: "B3A4F9" },
    { token: "support.function", foreground: "B3A4F9" },
    { token: "support.class", foreground: "B3A4F9" },
    { token: "support.type", foreground: "B3A4F9" },
    { token: "type", foreground: "B3A4F9" },
    { token: "variable", foreground: "e8e8e8" },
    { token: "variable.parameter", foreground: "e8e8e8" },
    { token: "identifier", foreground: "e8e8e8" },
    { token: "punctuation", foreground: "e8e8e8" },
    { token: "delimiter", foreground: "e8e8e8" },
    { token: "operator", foreground: "999999" },
    { token: "tag", foreground: "B3A4F9" },
    { token: "tag.attribute.name", foreground: "e8e8e8" },
    { token: "attribute.name", foreground: "e8e8e8" },
    { token: "attribute.value", foreground: "99FFE4" },
    { token: "metatag", foreground: "999999" },
    { token: "regexp", foreground: "99FFE4" },
    { token: "bold", fontStyle: "bold" },
    { token: "italic", fontStyle: "italic" },
  ],
  colors: {
    "editor.background": "#101010",
    "editor.foreground": "#e8e8e8",
    "editor.lineHighlightBackground": "#181818",
    "editor.selectionBackground": "#2a2a40",
    "editor.selectionHighlightBackground": "#20203a",
    "editorCursor.foreground": "#e8e8e8",
    "editorLineNumber.foreground": "#404040",
    "editorLineNumber.activeForeground": "#686868",
    "editorIndentGuide.background1": "#1e1e1e",
    "editorIndentGuide.activeBackground1": "#333333",
    "editorWhitespace.foreground": "#2a2a2a",
    "editorBracketMatch.background": "#2a2a40",
    "editorBracketMatch.border": "#444488",
    "editor.findMatchBackground": "#2a2a40",
    "editor.findMatchHighlightBackground": "#1a1a30",
    "editorWidget.background": "#181818",
    "editorWidget.border": "#282828",
    "editorSuggestWidget.background": "#181818",
    "editorSuggestWidget.border": "#282828",
    "editorSuggestWidget.selectedBackground": "#2a2a2a",
    "editorHoverWidget.background": "#181818",
    "editorHoverWidget.border": "#282828",
    "scrollbarSlider.background": "#2a2a2a80",
    "scrollbarSlider.hoverBackground": "#3a3a3a80",
    "scrollbarSlider.activeBackground": "#4a4a4a80",
    "minimap.background": "#101010",
  },
};

export const VESPER_LIGHT_THEME_DATA: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: false,
  rules: [
    { token: "", foreground: "24292e", background: "fafbfc" },
    { token: "comment", foreground: "6a737d", fontStyle: "italic" },
    { token: "comment.line", foreground: "6a737d", fontStyle: "italic" },
    { token: "comment.block", foreground: "6a737d", fontStyle: "italic" },
    { token: "string", foreground: "22863a" },
    { token: "string.escape", foreground: "22863a" },
    { token: "string.quoted", foreground: "22863a" },
    { token: "string.template", foreground: "22863a" },
    { token: "number", foreground: "b08800" },
    { token: "number.float", foreground: "b08800" },
    { token: "number.hex", foreground: "b08800" },
    { token: "constant.numeric", foreground: "b08800" },
    { token: "keyword", foreground: "d73a49" },
    { token: "keyword.control", foreground: "d73a49" },
    { token: "keyword.operator", foreground: "d73a49" },
    { token: "storage", foreground: "d73a49" },
    { token: "storage.type", foreground: "d73a49" },
    { token: "entity.name.function", foreground: "6f42c1" },
    { token: "entity.name.type", foreground: "6f42c1" },
    { token: "entity.name.class", foreground: "6f42c1" },
    { token: "support.function", foreground: "6f42c1" },
    { token: "support.class", foreground: "6f42c1" },
    { token: "support.type", foreground: "6f42c1" },
    { token: "type", foreground: "6f42c1" },
    { token: "variable", foreground: "24292e" },
    { token: "variable.parameter", foreground: "e36209" },
    { token: "identifier", foreground: "24292e" },
    { token: "punctuation", foreground: "24292e" },
    { token: "delimiter", foreground: "24292e" },
    { token: "operator", foreground: "d73a49" },
    { token: "tag", foreground: "22863a" },
    { token: "tag.attribute.name", foreground: "6f42c1" },
    { token: "attribute.name", foreground: "6f42c1" },
    { token: "attribute.value", foreground: "032f62" },
    { token: "metatag", foreground: "d73a49" },
    { token: "regexp", foreground: "032f62" },
    { token: "bold", fontStyle: "bold" },
    { token: "italic", fontStyle: "italic" },
  ],
  colors: {
    "editor.background": "#fafbfc",
    "editor.foreground": "#24292e",
    "editor.lineHighlightBackground": "#f1f3f5",
    "editor.selectionBackground": "#c8d1f0",
    "editor.selectionHighlightBackground": "#dde4f8",
    "editorCursor.foreground": "#24292e",
    "editorLineNumber.foreground": "#9ca3af",
    "editorLineNumber.activeForeground": "#6b7280",
    "editorIndentGuide.background1": "#e5e7eb",
    "editorIndentGuide.activeBackground1": "#d1d5db",
    "editorWhitespace.foreground": "#e5e7eb",
    "editorBracketMatch.background": "#dde4f8",
    "editorBracketMatch.border": "#8b9cf0",
    "editor.findMatchBackground": "#fce4b8",
    "editor.findMatchHighlightBackground": "#fef3d6",
    "editorWidget.background": "#f3f4f6",
    "editorWidget.border": "#d1d5db",
    "editorSuggestWidget.background": "#f3f4f6",
    "editorSuggestWidget.border": "#d1d5db",
    "editorSuggestWidget.selectedBackground": "#e5e7eb",
    "editorHoverWidget.background": "#f3f4f6",
    "editorHoverWidget.border": "#d1d5db",
    "scrollbarSlider.background": "#9ca3af50",
    "scrollbarSlider.hoverBackground": "#6b728060",
    "scrollbarSlider.activeBackground": "#4b556370",
    "minimap.background": "#fafbfc",
  },
};
