import type { editor } from "monaco-editor";

export const VESPER_THEME_NAME = "vesper";

// Vesper theme for Monaco — bg #101010, mint strings, lavender functions
export const VESPER_THEME_DATA: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "e8e8e8", background: "101010" },
    { token: "comment", foreground: "585858", fontStyle: "italic" },
    { token: "comment.line", foreground: "585858", fontStyle: "italic" },
    { token: "comment.block", foreground: "585858", fontStyle: "italic" },
    { token: "string", foreground: "99FFE4" },
    { token: "string.escape", foreground: "99FFE4" },
    { token: "string.quoted", foreground: "99FFE4" },
    { token: "string.template", foreground: "99FFE4" },
    { token: "number", foreground: "dbb96e" },
    { token: "number.float", foreground: "dbb96e" },
    { token: "number.hex", foreground: "dbb96e" },
    { token: "constant.numeric", foreground: "dbb96e" },
    { token: "keyword", foreground: "999999" },
    { token: "keyword.control", foreground: "999999" },
    { token: "keyword.operator", foreground: "999999" },
    { token: "storage", foreground: "999999" },
    { token: "storage.type", foreground: "999999" },
    { token: "entity.name.function", foreground: "B3A4F9" },
    { token: "entity.name.type", foreground: "B3A4F9" },
    { token: "entity.name.class", foreground: "B3A4F9" },
    { token: "support.function", foreground: "B3A4F9" },
    { token: "support.class", foreground: "B3A4F9" },
    { token: "support.type", foreground: "B3A4F9" },
    { token: "type", foreground: "B3A4F9" },
    { token: "variable", foreground: "e8e8e8" },
    { token: "variable.parameter", foreground: "e8e8e8" },
    { token: "identifier", foreground: "e8e8e8" },
    { token: "punctuation", foreground: "e8e8e8" },
    { token: "delimiter", foreground: "e8e8e8" },
    { token: "operator", foreground: "999999" },
    { token: "tag", foreground: "B3A4F9" },
    { token: "tag.attribute.name", foreground: "e8e8e8" },
    { token: "attribute.name", foreground: "e8e8e8" },
    { token: "attribute.value", foreground: "99FFE4" },
    { token: "metatag", foreground: "999999" },
    { token: "regexp", foreground: "99FFE4" },
    { token: "bold", fontStyle: "bold" },
    { token: "italic", fontStyle: "italic" },
  ],
  colors: {
    "editor.background": "#101010",
    "editor.foreground": "#e8e8e8",
    "editor.lineHighlightBackground": "#181818",
    "editor.selectionBackground": "#2a2a40",
    "editor.selectionHighlightBackground": "#20203a",
    "editorCursor.foreground": "#e8e8e8",
    "editorLineNumber.foreground": "#404040",
    "editorLineNumber.activeForeground": "#686868",
    "editorIndentGuide.background1": "#1e1e1e",
    "editorIndentGuide.activeBackground1": "#333333",
    "editorWhitespace.foreground": "#2a2a2a",
    "editorBracketMatch.background": "#2a2a40",
    "editorBracketMatch.border": "#444488",
    "editor.findMatchBackground": "#2a2a40",
    "editor.findMatchHighlightBackground": "#1a1a30",
    "editorWidget.background": "#181818",
    "editorWidget.border": "#282828",
    "editorSuggestWidget.background": "#181818",
    "editorSuggestWidget.border": "#282828",
    "editorSuggestWidget.selectedBackground": "#2a2a2a",
    "editorHoverWidget.background": "#181818",
    "editorHoverWidget.border": "#282828",
    "scrollbarSlider.background": "#2a2a2a80",
    "scrollbarSlider.hoverBackground": "#3a3a3a80",
    "scrollbarSlider.activeBackground": "#4a4a4a80",
    "minimap.background": "#101010",
  },
};
